Update sway-toggle, alacritty
- Remove prettier in mason

diff --git a/bin/.local/bin/sway-scratch-toggle b/bin/.local/bin/sway-scratch-toggle
--- a/bin/.local/bin/sway-scratch-toggle
+++ b/bin/.local/bin/sway-scratch-toggle
@@ -15,36 +15,46 @@
 # sway-scratch-toggle alacritty "app_id,alacritty" "resize set 1080 768"
 #
 
+swayCommands=$1
+shift
+
+appType=$(echo "$1" | cut -d ',' -f 1)
+appId=$(echo "$1" | cut -d ',' -f 2)
+shift
+
 app=$1
 
-if [ -z "$app" ] || [ -z "$2" ]; then
+script=$(basename "$0")
+
+if [ -z "$app" ] || [ -z "$appType" ] || [ -z "$appId" ]; then
   printf "app name and identifier are required!\n
   Supported applications will be spawned with given identifier.\n
   - Sway commands are optional
   Examples:\n
-  \t $(basename $0) app_name '<class|app_id>,<identifier>' 'Sway commands'\n\n
-  \t $(basename $0) spotify 'class,Spotify' 'resize set 1280 920'\n
-  \t $(basename $0) alacritty 'app_id,alacritty' 'resize set 1080 768'\n
-  "
+  \t %s 'Sway commands' '<class|app_id>,<identifier>' app_name\n\n
+  \t %s 'resize set 1280 920' 'class,Spotify' spotify\n
+  \t %s 'resize set 1080 768' 'app_id,alacritty' alacritty\n
+  " "$script" "$script" "$script"
   exit 1
 fi
 
-appType=$(echo "$2" | cut -d ',' -f 1)
-appId=$(echo "$2" | cut -d ',' -f 2)
+isAppOpen=$(
+  swaymsg -t get_tree | grep -i "\"$appType\": \"$appId\""
+  echo $?
+)
 
-swayCommands=${3:-''}
+# Check if grep's exit code is 0, then it found a match,
+# any code except 0 exit codes, that means the app isn't open
+if [ "$isAppOpen" -ne 0 ]; then
 
-isOpen=$(swaymsg -t get_tree | grep -i "\"$appType\": \"$appId\"")
+  ("$HOME/.local/bin/run-with-sway-command" "scratchpad show" "$app" --class "$appId" ||
+    "$HOME/.local/bin/run-with-sway-command" "scratchpad show" "$app") &
+  sleep 1 && {
+    swaymsg "[$appType=\"$appId\"] floating enable"
+    swaymsg "[$appType=\"$appId\"] $swayCommands"
+  }
 
-toggle_scratch() {
-
+else
+  # toggle scratch
   swaymsg "[$appType=\"$appId\"] scratchpad show"
-}
-
-if [ -z "$isOpen" ]; then
-  exec "$HOME/.local/bin/run-with-sway-command" "move to scratchpad, $swayCommands" "$app" --class "$appId"
 fi
-
-sleep 0.1
-
-toggle_scratch
